version: '3.9'
services:
  # app
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - fe-product-www:/var/www/app
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - LOG_LEVEL=error
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
    networks:
      - fe-product-network-prod

  # nginx
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - fe-product-www:/var/www/app
    environment:
      NGINX_PORT: 80
      PHP_FPM_HOST: app
      PHP_FPM_PORT: 9000
      ROOT_FOLDER: /var/www/app/public
    ports:
      - "8001:80"
    networks:
      - fe-product-network-prod

volumes:
  fe-product-www:

networks:
  fe-product-network-prod:
    driver: bridge